### ISSUE TITLE
Heavy Ship Unit Model Appearing as Tier 1 Land Unit

### ISSUE THREAD

**Issue by DarthVenator** [Victorum-Universalis-VU/Victorum-Universalis#14] opened 2021-07-17 00:10 UTC
Whenever you pass mil tech 32, the models for the heavy ships become the tier 1 unit models/
![debug](https://user-images.githubusercontent.com/87551870/126019212-8783950a-1c8c-4899-b973-b0b9ec766812.PNG)

**Comment by slamchan** [comment] 2021-07-17 00:32
I would imagine this is because all ships after vanilla ones are missing models and/or animamtions. A quick look around files would confirm this.

**Comment by letole** [comment] 2021-07-17 18:41
The problem with the unit models is that there is no lvl 6 ship sprite. I will set it to lvl 5 so that it works.

74s have less guns than threedecker. I will change that.

**Comment by letole** [comment] 2021-07-17 19:04
okay, it is not the lvl 5 thing. the sprites haven't been defined

**Comment by slamchan** [comment] 2021-07-17 19:10
I too tried to find the reason for hours and didn't find it :V

**Comment by letole** [comment] 2021-07-17 19:17
okay, I found the problem. There are no sprites for the higher level ships. This means that it defaults to normal units. I can probably fix this but I have never done so before so it will take some time.

**Comment by letole** [comment] 2021-08-02 13:33
I have updated it so that they use the highest lvl ship as unit model

**Comment by slamchan** [comment] 2021-08-09 15:12
Seems like the issue is resolved. Closing

**Closed by slamchan** 2021-08-09 15:12 UTC
Labels: bug
